Don't optimize every day

diff --git a/cleanup/updater b/cleanup/updater
--- a/cleanup/updater
+++ b/cleanup/updater
@@ -111,6 +111,7 @@ while sleep 120; do
   LAST_LOG_FILE3=${LOG_BASE}.old.2
   LAST_LOG_FILE4=${LOG_BASE}.old.3
   RELEASE_LOG_FILE=${LOG_BASE}.release.log
+  GIT_OPTIMISE=${LOG_BASE}.optimise
 
   echo "Rotating log files"
   [ -f "${LOG_FILE}" ] && grep RELEASE "${LOG_FILE}" >> "${RELEASE_LOG_FILE}"
@@ -146,5 +147,18 @@ while sleep 120; do
   } 2>&1 | tee "${LOG_FILE}"
   echo "Done"
 
-  "$BASEDIR/optimise-git" || die "GIT optimise failed"
+  echo "Git Optimise"
+  WEEKDAY=$(date +%u)
+  if [ $GIT_OPTIMIZE_DAY = $WEEKDAY ]; then
+    if [ ! -f "$GIT_OPTIMISE" ]; then
+      echo " -- Optimising"
+      touch "$GIT_OPTIMISE"
+      "$BASEDIR/optimise-git" || die "GIT optimise failed"
+    else
+      echo " -- Not optimising - already run today"
+    fi
+  else
+    echo " -- Not optimising today"
+    rm -fr "$GIT_OPTIMISE"
+  fi
 done
