Stack names

diff --git a/update b/update
--- a/update
+++ b/update
@@ -75,7 +75,7 @@ cp "$BASEDIR/scripts/setup-gpg" "$BASEDIR/templates/"
 echo "Updating docker"
 sudo docker compose pull || die "Failed to pull images"
 sudo docker compose build || die "Failed to build images"
-sudo docker compose up -d --remove-orphans --project-name "$COMPOSE_PROJECT_NAME" || die "Failed to bring up services"
+sudo docker compose up -d --remove-orphans || die "Failed to bring up services"
 
 echo "Removing old images"
 sudo docker image prune -f || die "Failed to prune old images"
