Added profiles

diff --git a/update b/update
--- a/update
+++ b/update
@@ -81,7 +81,7 @@ sudo docker compose build || die "Failed to build images"
 if [ -z "$COMPOSE_PROFILE" ]; then
   sudo docker compose up -d --remove-orphans || die "Failed to bring up services"
 else
-  sudo docker compose up -d --remove-orphans --profile "$COMPOSE_PROFILE" || die "Failed to bring up services"
+  sudo docker compose --profile "$COMPOSE_PROFILE" up -d --remove-orphans  || die "Failed to bring up services"
 fi
 echo "Removing old images"
 sudo docker image prune -f || die "Failed to prune old images"
