changing to dir

diff --git a/update b/update
--- a/update
+++ b/update
@@ -10,6 +10,8 @@ die() {
 BASEDIR="$(dirname "$(readlink -f "$0")")"
 echo "Script Dir: $BASEDIR"
 
+cd "$BASEDIR" || die "Could not change to $BASEDIR"
+
 [ -f "$BASEDIR/.env" ] || die ".env is required"
 
 echo "Updating Repo"
