Project name

diff --git a/update b/update
--- a/update
+++ b/update
@@ -73,11 +73,11 @@ cp "$BASEDIR/scripts/setup-git" "$BASEDIR/templates/"
 cp "$BASEDIR/scripts/setup-gpg" "$BASEDIR/templates/"
 
 echo "Updating docker"
-sudo docker compose pull --project-name "$ENV_PREFIX" \
-  && sudo docker compose build --project-name "$ENV_PREFIX" \
-  && sudo docker compose up -d --remove-orphans --project-name "$ENV_PREFIX"
+sudo docker compose pull || die "Failed to pull images"
+sudo docker compose build --project-name "$ENV_PREFIX" || die "Failed to build images"
+sudo docker compose up -d --remove-orphans --project-name "$ENV_PREFIX" || die "Failed to bring up services"
 
 echo "Removing old images"
-sudo docker image prune -f
+sudo docker image prune -f || die "Failed to prune old images"
 
 echo "Done"
