Better locking

diff --git a/dependencies/updater b/dependencies/updater
--- a/dependencies/updater
+++ b/dependencies/updater
@@ -119,16 +119,19 @@ while sleep 120; do
     "$DOTNET_ROOT/dotnet" tool update --local Credfeto.DotNet.Repo.Tools.Cmd
     "$DOTNET_ROOT/dotnet" tool list
     date
-  } > "${LOG_BASE}.install" 2>&1
+  }  2>&1 | tee "${LOG_BASE}.install"
 
-  echo "Running tool"
-  "$DOTNET_ROOT/dotnet" updaterepo \
+
+  {
+    echo "Running tool"
+    "$DOTNET_ROOT/dotnet" updaterepo \
           reduce-dependencies \
-            --repositories "${REPOS_LIST}" \
-            --work "${WORK}" \
-            --tracking "${TRACKING_FILE}" \
-            --template "${TEMPLATE}" \
-               2>&1 | tee "${LOG_FILE}"
+              --repositories "${REPOS_LIST}" \
+              --work "${WORK}" \
+              --tracking "${TRACKING_FILE}" \
+              --template "${TEMPLATE}" \
+        || die "Update failed"
+  } 2>&1 | tee "${LOG_FILE}"
 
   echo "Done"
 
