Using updated script

diff --git a/templates/updater b/templates/updater
--- a/templates/updater
+++ b/templates/updater
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /bin/bash
 
 
 die() {
@@ -65,6 +65,7 @@ export DOTNET_TC_CallCountingDelayMs="0"
 export DOTNET_TieredPGO="1"
 export MSBUILDTERMINALLOGGER="auto"
 
+[ -f "/bin/curl" ] || die "cur not found"
 [ -f "/bin/tar" ] || die "tar not found"
 
 . "$BASEDIR/install-dotnet"
