Git optimise

diff --git a/templates/updater b/templates/updater
--- a/templates/updater
+++ b/templates/updater
@@ -147,4 +147,6 @@ while sleep 120; do
               2>&1 | tee "${LOG_FILE}"
 
   echo "Done"
+
+  "$BASEDIR/optimise-git" || die "GIT optimise failed"
 done
